### ISSUE TITLE
Exception in thread "main" java.lang.UnsupportedClassVersionError: 

### ISSUE THREAD

**Issue by jsaade** [sjitech/ApkRename#1]
~~~~ change package name of AndroidManifest.xml
Exception in thread "main" java.lang.UnsupportedClassVersionError: jp/sji/sumatium/tool/AndroidManifestBinaryXml_ChangePackageName : Unsupported major.minor version 51.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
    at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)

**Comment by jjqq2013** [comment]
Maybe you need use Java 8  (Install JDK 1.8 and set java 1.8 to PATH
environment variable)

2015-01-12 23:19 GMT+09:00 jsaade notifications@github.com:

**Comment by tanius** [comment]
I also had this issue, and the proposal to install Java 8 solved it. I had Java 7 before.
